Update ensure logic #3

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -4,21 +4,25 @@ on:
     branches: [frontend_dev]
 
 jobs:
-  # lint:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #       with:
-  #         ref: 'frontend_dev'
-      
-  #     - name: Install dependences
-  #       run: npm i
+  check-backend-changes:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: frontend_dev
 
-  #     - name: Lint
-  #       run: npm run lint
+      - name: Check for changes in backend
+        run: |
+          if git diff --name-only origin/frontend_dev | grep '^backend/'; then
+            echo "Changes detected in the backend folder. Failing the check."
+            exit 1
+          else
+            echo "No changes in the backend folder."
+          fi
 
   merge:
+    needs: check-backend-changes
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -26,16 +30,7 @@ jobs:
         with:
           ref: frontend_dev
         
-      - name: Ensure no changes in backend directory
-        run: |
-          if git diff --name-only | grep '^backend/*'; then
-            echo "backend_modified=true" >> $GITHUB_ENV
-          else
-            echo "backend_modified=false" >> $GITHUB_ENV
-          fi
-
       - name: Create PR to dev
-        if: env.backend_modified == 'true'
         uses: peter-evans/create-pull-request@v7
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
